# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf13c6d66c981b04bab3aa70cbd100d0e2e6b863cc9b920ce241ffdb40924b118863e00a1f8a20d174519b4908b35347a9d83ad4cbe8c52dc19346f9b3e4213b

test:
  secret_key_base: 3c725e9e97215539a3f8ae657e47f1618fdad0cf4a2dd108dfa6bce2120e4d06e7fb0d92f90903c68c22eaea2cddbe1e105d839b24bc1fda8e2e25a8551bf564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
